<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesPersonProxy extends \Entities\Person implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function offsetExists($offset)
    {
        $this->__load();
        return parent::offsetExists($offset);
    }

    public function offsetSet($offset, $value)
    {
        $this->__load();
        return parent::offsetSet($offset, $value);
    }

    public function offsetGet($offset)
    {
        $this->__load();
        return parent::offsetGet($offset);
    }

    public function offsetUnset($offset)
    {
        $this->__load();
        return parent::offsetUnset($offset);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setEmails(\Entities\Email $emails = NULL)
    {
        $this->__load();
        return parent::setEmails($emails);
    }

    public function getEmails()
    {
        $this->__load();
        return parent::getEmails();
    }

    public function addEmail(\Entities\Email $email)
    {
        $this->__load();
        return parent::addEmail($email);
    }

    public function removeEmail(\Entities\Email $email)
    {
        $this->__load();
        return parent::removeEmail($email);
    }

    public function setPhonenumbers(\Entities\Phonenumber $phonenumbers = NULL)
    {
        $this->__load();
        return parent::setPhonenumbers($phonenumbers);
    }

    public function getPhonenumbers()
    {
        $this->__load();
        return parent::getPhonenumbers();
    }

    public function addPhonenumber(\Entities\Phonenumber $phonenumber)
    {
        $this->__load();
        return parent::addPhonenumber($phonenumber);
    }

    public function removePhonenumber(\Entities\Phonenumber $phonenumber)
    {
        $this->__load();
        return parent::removePhonenumber($phonenumber);
    }

    public function setFaxnumbers(\Entities\Faxnumber $faxnumbers = NULL)
    {
        $this->__load();
        return parent::setFaxnumbers($faxnumbers);
    }

    public function getFaxnumbers()
    {
        $this->__load();
        return parent::getFaxnumbers();
    }

    public function addFaxnumber(\Entities\Faxnumber $faxnumber)
    {
        $this->__load();
        return parent::addFaxnumber($faxnumber);
    }

    public function removeFaxnumber(\Entities\Faxnumber $phonenumber)
    {
        $this->__load();
        return parent::removeFaxnumber($phonenumber);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setAddress(\Entities\Address $address = NULL)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getProfile()
    {
        $this->__load();
        return parent::getProfile();
    }

    public function setProfile(\Entities\Profile $profile = NULL)
    {
        $this->__load();
        return parent::setProfile($profile);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setAccount(\Entities\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getEthnicity()
    {
        $this->__load();
        return parent::getEthnicity();
    }

    public function setEthnicity(\Entities\Ethnicity $ethnicity)
    {
        $this->__load();
        return parent::setEthnicity($ethnicity);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getCitizenship()
    {
        $this->__load();
        return parent::getCitizenship();
    }

    public function setCitizenship($citizenship)
    {
        $this->__load();
        return parent::setCitizenship($citizenship);
    }

    public function onPreUpdate()
    {
        $this->__load();
        return parent::onPreUpdate();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'firstname', 'lastname', 'gender', 'citizenship', 'notes', 'created', 'updated', 'status', 'emails', 'phonenumbers', 'faxnumbers', 'ethnicity', 'address', 'profile', 'account');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}