<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ApiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiRepository extends EntityRepository
{
    /**
     * (non-PHPdoc)
     * @see Doctrine\ORM.EntityRepository::findAll()
     */
    public function findAll() {
        $query = $this->_em
            ->createQuery('
                SELECT ap, m, ac FROM Entities\Api ap
                LEFT JOIN ap.maintainer m
                LEFT JOIN ap.actions ac
                INDEX BY ap.name
                ORDER BY ap.name
            ');

        /* I've set the cache driver to APC in SilexProvider\Doctrine2ServiceProvider.php */
        $query->useResultCache(true);
        /* extra long since it won't change much */
        $query->setResultCacheLifetime(36000);

        /* array is better and we really don't need objects right now */
        return $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }


    /**
     * Finds all API names
     *
     * @return mixed
     */
    public function findAllApiNames() {
        $query = $this->_em
            ->createQuery('
                SELECT ap.name FROM Entities\Api ap
                INDEX BY ap.name
                ORDER BY ap.name
            ');

        /* array is better and we really don't need objects right now */
        return $query->getResult(\Doctrine\ORM\Query::HYDRATE_SCALAR);
    }
}
