<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionRepository extends EntityRepository
{
    /**
     * (non-PHPdoc)
     * @see Doctrine\ORM.EntityRepository::findAll()
     */
    public function findAllByPartialName($term) {
        $query = $this->_em
            ->createQuery('
                SELECT i.id as value, i.name as label
                FROM Entities\Institution i
                WHERE i.name LIKE :partial_name
                ORDER BY i.name
            ');

        $query->setParameter('partial_name', "%$term%");

        /* I've set the cache driver to APC in SilexProvider\Doctrine2ServiceProvider.php */
        $query->useResultCache(true);
        /* extra long since it won't change much */
        $query->setResultCacheLifetime(36000);

        /* array is better and we really don't need objects right now */
        return $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }

}
