<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
    /*public function findAllByUserId($id) {
        $query = $this->_em
            ->createQuery(
                '
                SELECT tk, u FROM Entities\Tokens tk
                JOIN tk.account u
                '
            );
        $query->setParameter('person_id', $person_id);

        return $query->getSingleResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
    }*/

}
