<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrellisUserApiClientRepository extends EntityRepository
{
    /**
     * Find 1 User API Client by its key
     *
     * NoUniqueException is thrown if more than one. Since we are finding by
     * key, this ought not happen...
     *
     * @param int $key
     *
     * @return ServiceRequest
     */
    public function findOneByKey($client_key)
    {
        $client_query = $this->_em->createQuery("
            SELECT tapc FROM Entities\ApiClient\TrellisUserApiClient tapc
            WHERE
                tapc.api_key = :key
        ");
            
        $client_query->setParameters(array(
            'key'=> $client_key,
        ));

        return $client_query->getSingleResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
    }
}
